name: Car Availability Test

on:
  workflow_dispatch:
  schedule:
    - cron: '15 6 * * *' # 10:15 AM Dubai

jobs:
  car-availability-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests pytz --break-system-packages

      - name: Run Car Availability Test
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          APPIC_KEY: ${{ secrets.APPIC_KEY }}
        run: python mkv_car_availbaility.py
